version: 2
updates:
  - package-ecosystem: "npm"
    directory: /
    schedule:
      interval: "weekly"
    group: "all"
    commit-message:
      prefix: "fix(deps)"
    auto-merge:
      enable: true
      method: "merge"
  - package-ecosystem: "docker"
    directory: /
    schedule:
      interval: "weekly"
    group: "all"
    commit-message:
      prefix: "fix(deps)"
    auto-merge:
      enable: true
      method: "merge"
