-- Optional audit before hard cleanup
-- Reports which legacy camelCase columns can be dropped safely.
WITH mapping(schema_name, table_name, legacy_col, snake_col) AS (
  VALUES
  ('public', 'achievement_definitions', 'createdAt', 'created_at'),
  ('public', 'achievement_definitions', 'isActive', 'is_active'),
  ('public', 'achievement_definitions', 'isRepeatable', 'is_repeatable'),
  ('public', 'achievement_definitions', 'updatedAt', 'updated_at'),
  ('public', 'adaptive_recommendations', 'appliedAt', 'applied_at'),
  ('public', 'adaptive_recommendations', 'createdAt', 'created_at'),
  ('public', 'adaptive_recommendations', 'currentValue', 'current_value'),
  ('public', 'adaptive_recommendations', 'exerciseId', 'exercise_id'),
  ('public', 'adaptive_recommendations', 'inputSnapshot', 'input_snapshot'),
  ('public', 'adaptive_recommendations', 'modelVersion', 'model_version'),
  ('public', 'adaptive_recommendations', 'reasonCode', 'reason_code'),
  ('public', 'adaptive_recommendations', 'recommendationType', 'recommendation_type'),
  ('public', 'adaptive_recommendations', 'sessionExerciseId', 'session_exercise_id'),
  ('public', 'adaptive_recommendations', 'suggestedValue', 'suggested_value'),
  ('public', 'adaptive_recommendations', 'updatedAt', 'updated_at'),
  ('public', 'adaptive_recommendations', 'userId', 'user_id'),
  ('public', 'adaptive_recommendations', 'validUntil', 'valid_until'),
  ('public', 'ai_coach_messages', 'completionTokens', 'completion_tokens'),
  ('public', 'ai_coach_messages', 'conversationKey', 'conversation_key'),
  ('public', 'ai_coach_messages', 'createdAt', 'created_at'),
  ('public', 'ai_coach_messages', 'insightId', 'insight_id'),
  ('public', 'ai_coach_messages', 'modelName', 'model_name'),
  ('public', 'ai_coach_messages', 'promptTokens', 'prompt_tokens'),
  ('public', 'ai_coach_messages', 'sessionId', 'session_id'),
  ('public', 'ai_coach_messages', 'updatedAt', 'updated_at'),
  ('public', 'ai_coach_messages', 'userId', 'user_id'),
  ('public', 'ai_insights', 'createdAt', 'created_at'),
  ('public', 'ai_insights', 'insightType', 'insight_type'),
  ('public', 'ai_insights', 'modelVersion', 'model_version'),
  ('public', 'ai_insights', 'sessionId', 'session_id'),
  ('public', 'ai_insights', 'tokensUsed', 'tokens_used'),
  ('public', 'ai_insights', 'updatedAt', 'updated_at'),
  ('public', 'ai_insights', 'userId', 'user_id'),
  ('public', 'challenge_participants', 'challengeId', 'challenge_id'),
  ('public', 'challenge_participants', 'completedAt', 'completed_at'),
  ('public', 'challenge_participants', 'createdAt', 'created_at'),
  ('public', 'challenge_participants', 'joinedAt', 'joined_at'),
  ('public', 'challenge_participants', 'progressValue', 'progress_value'),
  ('public', 'challenge_participants', 'updatedAt', 'updated_at'),
  ('public', 'challenge_participants', 'userId', 'user_id'),
  ('public', 'challenges', 'challengeType', 'challenge_type'),
  ('public', 'challenges', 'createdAt', 'created_at'),
  ('public', 'challenges', 'creatorId', 'creator_id'),
  ('public', 'challenges', 'endDate', 'end_date'),
  ('public', 'challenges', 'isPublic', 'is_public'),
  ('public', 'challenges', 'startDate', 'start_date'),
  ('public', 'challenges', 'targetValue', 'target_value'),
  ('public', 'challenges', 'updatedAt', 'updated_at'),
  ('public', 'exercise_aliases', 'createdAt', 'created_at'),
  ('public', 'exercise_aliases', 'exerciseId', 'exercise_id'),
  ('public', 'exercise_aliases', 'normalizedAlias', 'normalized_alias'),
  ('public', 'exercise_aliases', 'updatedAt', 'updated_at'),
  ('public', 'exercise_personal_records', 'achievedAt', 'achieved_at'),
  ('public', 'exercise_personal_records', 'createdAt', 'created_at'),
  ('public', 'exercise_personal_records', 'exerciseId', 'exercise_id'),
  ('public', 'exercise_personal_records', 'sourceSessionId', 'source_session_id'),
  ('public', 'exercise_personal_records', 'sourceWorkoutSetId', 'source_workout_set_id'),
  ('public', 'exercise_personal_records', 'updatedAt', 'updated_at'),
  ('public', 'exercise_personal_records', 'userId', 'user_id'),
  ('public', 'exercises', 'createdAt', 'created_at'),
  ('public', 'exercises', 'isArchived', 'is_archived'),
  ('public', 'exercises', 'isPublic', 'is_public'),
  ('public', 'exercises', 'isUnilateral', 'is_unilateral'),
  ('public', 'exercises', 'ownerId', 'owner_id'),
  ('public', 'exercises', 'primaryMuscle', 'primary_muscle'),
  ('public', 'exercises', 'secondaryMuscles', 'secondary_muscles'),
  ('public', 'exercises', 'updatedAt', 'updated_at'),
  ('public', 'friendships', 'addresseeId', 'addressee_id'),
  ('public', 'friendships', 'createdAt', 'created_at'),
  ('public', 'friendships', 'requestedAt', 'requested_at'),
  ('public', 'friendships', 'requesterId', 'requester_id'),
  ('public', 'friendships', 'respondedAt', 'responded_at'),
  ('public', 'friendships', 'updatedAt', 'updated_at'),
  ('public', 'rest_timer_events', 'actualRestSec', 'actual_rest_sec'),
  ('public', 'rest_timer_events', 'createdAt', 'created_at'),
  ('public', 'rest_timer_events', 'eventType', 'event_type'),
  ('public', 'rest_timer_events', 'plannedRestSec', 'planned_rest_sec'),
  ('public', 'rest_timer_events', 'sessionExerciseId', 'session_exercise_id'),
  ('public', 'rest_timer_events', 'sessionId', 'session_id'),
  ('public', 'rest_timer_events', 'triggeredAt', 'triggered_at'),
  ('public', 'rest_timer_events', 'updatedAt', 'updated_at'),
  ('public', 'rest_timer_events', 'workoutSetId', 'workout_set_id'),
  ('public', 'social_reactions', 'createdAt', 'created_at'),
  ('public', 'social_reactions', 'postId', 'post_id'),
  ('public', 'social_reactions', 'reactionType', 'reaction_type'),
  ('public', 'social_reactions', 'updatedAt', 'updated_at'),
  ('public', 'social_reactions', 'userId', 'user_id'),
  ('public', 'social_workout_posts', 'createdAt', 'created_at'),
  ('public', 'social_workout_posts', 'isDeleted', 'is_deleted'),
  ('public', 'social_workout_posts', 'sessionId', 'session_id'),
  ('public', 'social_workout_posts', 'updatedAt', 'updated_at'),
  ('public', 'social_workout_posts', 'userId', 'user_id'),
  ('public', 'sync_events', 'clientEventId', 'client_event_id'),
  ('public', 'sync_events', 'conflictData', 'conflict_data'),
  ('public', 'sync_events', 'createdAt', 'created_at'),
  ('public', 'sync_events', 'deviceId', 'device_id'),
  ('public', 'sync_events', 'entityId', 'entity_id'),
  ('public', 'sync_events', 'entityType', 'entity_type'),
  ('public', 'sync_events', 'eventStatus', 'event_status'),
  ('public', 'sync_events', 'occurredAt', 'occurred_at'),
  ('public', 'sync_events', 'processedAt', 'processed_at'),
  ('public', 'sync_events', 'updatedAt', 'updated_at'),
  ('public', 'sync_events', 'userId', 'user_id'),
  ('public', 'training_program_weeks', 'createdAt', 'created_at'),
  ('public', 'training_program_weeks', 'programId', 'program_id'),
  ('public', 'training_program_weeks', 'updatedAt', 'updated_at'),
  ('public', 'training_program_weeks', 'weekNumber', 'week_number'),
  ('public', 'training_program_workouts', 'createdAt', 'created_at'),
  ('public', 'training_program_workouts', 'dayOfWeek', 'day_of_week'),
  ('public', 'training_program_workouts', 'orderIndex', 'order_index'),
  ('public', 'training_program_workouts', 'templateId', 'template_id'),
  ('public', 'training_program_workouts', 'updatedAt', 'updated_at'),
  ('public', 'training_program_workouts', 'weekId', 'week_id'),
  ('public', 'training_programs', 'authorId', 'author_id'),
  ('public', 'training_programs', 'createdAt', 'created_at'),
  ('public', 'training_programs', 'currencyCode', 'currency_code'),
  ('public', 'training_programs', 'isArchived', 'is_archived'),
  ('public', 'training_programs', 'isMarketplaceListed', 'is_marketplace_listed'),
  ('public', 'training_programs', 'isPublic', 'is_public'),
  ('public', 'training_programs', 'priceCents', 'price_cents'),
  ('public', 'training_programs', 'updatedAt', 'updated_at'),
  ('public', 'user_achievements', 'achievementDefinitionId', 'achievement_definition_id'),
  ('public', 'user_achievements', 'awardedAt', 'awarded_at'),
  ('public', 'user_achievements', 'createdAt', 'created_at'),
  ('public', 'user_achievements', 'updatedAt', 'updated_at'),
  ('public', 'user_achievements', 'userId', 'user_id'),
  ('public', 'user_profiles', 'birthDate', 'birth_date'),
  ('public', 'user_profiles', 'bodyFatPercent', 'body_fat_percent'),
  ('public', 'user_profiles', 'createdAt', 'created_at'),
  ('public', 'user_profiles', 'displayName', 'display_name'),
  ('public', 'user_profiles', 'firstName', 'first_name'),
  ('public', 'user_profiles', 'heightCm', 'height_cm'),
  ('public', 'user_profiles', 'lastName', 'last_name'),
  ('public', 'user_profiles', 'updatedAt', 'updated_at'),
  ('public', 'user_profiles', 'userId', 'user_id'),
  ('public', 'user_profiles', 'weightKg', 'weight_kg'),
  ('public', 'user_streaks', 'createdAt', 'created_at'),
  ('public', 'user_streaks', 'currentCount', 'current_count'),
  ('public', 'user_streaks', 'isActive', 'is_active'),
  ('public', 'user_streaks', 'lastEventDate', 'last_event_date'),
  ('public', 'user_streaks', 'longestCount', 'longest_count'),
  ('public', 'user_streaks', 'streakStartDate', 'streak_start_date'),
  ('public', 'user_streaks', 'streakType', 'streak_type'),
  ('public', 'user_streaks', 'updatedAt', 'updated_at'),
  ('public', 'user_streaks', 'userId', 'user_id'),
  ('public', 'users', 'createdAt', 'created_at'),
  ('public', 'users', 'deletedAt', 'deleted_at'),
  ('public', 'users', 'isOnboarded', 'is_onboarded'),
  ('public', 'users', 'telegramUserId', 'telegram_user_id'),
  ('public', 'users', 'telegramUsername', 'telegram_username'),
  ('public', 'users', 'updatedAt', 'updated_at'),
  ('public', 'workout_session_exercises', 'avgRpe', 'avg_rpe'),
  ('public', 'workout_session_exercises', 'bestEstimated1Rm', 'best_estimated1_rm'),
  ('public', 'workout_session_exercises', 'blockKey', 'block_key'),
  ('public', 'workout_session_exercises', 'blockType', 'block_type'),
  ('public', 'workout_session_exercises', 'createdAt', 'created_at'),
  ('public', 'workout_session_exercises', 'exerciseId', 'exercise_id'),
  ('public', 'workout_session_exercises', 'orderIndex', 'order_index'),
  ('public', 'workout_session_exercises', 'performedSets', 'performed_sets'),
  ('public', 'workout_session_exercises', 'sessionId', 'session_id'),
  ('public', 'workout_session_exercises', 'templateItemId', 'template_item_id'),
  ('public', 'workout_session_exercises', 'updatedAt', 'updated_at'),
  ('public', 'workout_session_exercises', 'volumeKg', 'volume_kg'),
  ('public', 'workout_sessions', 'createdAt', 'created_at'),
  ('public', 'workout_sessions', 'deletedAt', 'deleted_at'),
  ('public', 'workout_sessions', 'durationSeconds', 'duration_seconds'),
  ('public', 'workout_sessions', 'endedAt', 'ended_at'),
  ('public', 'workout_sessions', 'peakEstimated1RmKg', 'peak_estimated1_rm_kg'),
  ('public', 'workout_sessions', 'sessionFatigueScore', 'session_fatigue_score'),
  ('public', 'workout_sessions', 'sourceDeviceId', 'source_device_id'),
  ('public', 'workout_sessions', 'startedAt', 'started_at'),
  ('public', 'workout_sessions', 'syncVersion', 'sync_version'),
  ('public', 'workout_sessions', 'templateId', 'template_id'),
  ('public', 'workout_sessions', 'totalReps', 'total_reps'),
  ('public', 'workout_sessions', 'totalSets', 'total_sets'),
  ('public', 'workout_sessions', 'totalVolumeKg', 'total_volume_kg'),
  ('public', 'workout_sessions', 'trainingProgramWorkoutId', 'training_program_workout_id'),
  ('public', 'workout_sessions', 'updatedAt', 'updated_at'),
  ('public', 'workout_sessions', 'userId', 'user_id'),
  ('public', 'workout_sets', 'actualRestSec', 'actual_rest_sec'),
  ('public', 'workout_sets', 'createdAt', 'created_at'),
  ('public', 'workout_sets', 'distanceMeters', 'distance_meters'),
  ('public', 'workout_sets', 'durationSec', 'duration_sec'),
  ('public', 'workout_sets', 'estimated1RmKg', 'estimated1_rm_kg'),
  ('public', 'workout_sets', 'fatigueScore', 'fatigue_score'),
  ('public', 'workout_sets', 'isCompleted', 'is_completed'),
  ('public', 'workout_sets', 'sessionExerciseId', 'session_exercise_id'),
  ('public', 'workout_sets', 'setOrder', 'set_order'),
  ('public', 'workout_sets', 'setType', 'set_type'),
  ('public', 'workout_sets', 'suggestedRestSec', 'suggested_rest_sec'),
  ('public', 'workout_sets', 'updatedAt', 'updated_at'),
  ('public', 'workout_sets', 'weightKg', 'weight_kg'),
  ('public', 'workout_template_items', 'blockKey', 'block_key'),
  ('public', 'workout_template_items', 'blockType', 'block_type'),
  ('public', 'workout_template_items', 'createdAt', 'created_at'),
  ('public', 'workout_template_items', 'exerciseId', 'exercise_id'),
  ('public', 'workout_template_items', 'orderIndex', 'order_index'),
  ('public', 'workout_template_items', 'restSeconds', 'rest_seconds'),
  ('public', 'workout_template_items', 'targetRepsMax', 'target_reps_max'),
  ('public', 'workout_template_items', 'targetRepsMin', 'target_reps_min'),
  ('public', 'workout_template_items', 'targetRpe', 'target_rpe'),
  ('public', 'workout_template_items', 'targetSets', 'target_sets'),
  ('public', 'workout_template_items', 'targetWeightKg', 'target_weight_kg'),
  ('public', 'workout_template_items', 'templateId', 'template_id'),
  ('public', 'workout_template_items', 'updatedAt', 'updated_at'),
  ('public', 'workout_templates', 'createdAt', 'created_at'),
  ('public', 'workout_templates', 'estimatedMinSec', 'estimated_min_sec'),
  ('public', 'workout_templates', 'isArchived', 'is_archived'),
  ('public', 'workout_templates', 'isPublic', 'is_public'),
  ('public', 'workout_templates', 'updatedAt', 'updated_at'),
  ('public', 'workout_templates', 'userId', 'user_id')
), col_meta AS (
  SELECT m.*,
         to_regclass(format(%I.%I, m.schema_name, m.table_name)) AS relid,
         (SELECT attnum FROM pg_attribute WHERE attrelid = to_regclass(format(%I.%I, m.schema_name, m.table_name)) AND attname = m.legacy_col AND attnum > 0 AND NOT attisdropped) AS legacy_attnum,
         EXISTS (SELECT 1 FROM information_schema.columns c WHERE c.table_schema=m.schema_name AND c.table_name=m.table_name AND c.column_name=m.legacy_col) AS legacy_exists,
         EXISTS (SELECT 1 FROM information_schema.columns c WHERE c.table_schema=m.schema_name AND c.table_name=m.table_name AND c.column_name=m.snake_col) AS snake_exists
  FROM mapping m
), deps AS (
  SELECT cm.schema_name, cm.table_name, cm.legacy_col, count(*) AS dep_count
  FROM col_meta cm
  LEFT JOIN pg_depend d ON d.refobjid = cm.relid AND d.refobjsubid = cm.legacy_attnum AND d.deptype IN (n,a,i,e,x)
  GROUP BY cm.schema_name, cm.table_name, cm.legacy_col
)
SELECT cm.table_name, cm.legacy_col, cm.snake_col, cm.legacy_exists, cm.snake_exists, COALESCE(d.dep_count,0) AS dep_count,
       CASE
         WHEN NOT cm.legacy_exists THEN already_removed
         WHEN NOT cm.snake_exists THEN skip_snake_missing
         WHEN COALESCE(d.dep_count,0) > 0 THEN skip_has_dependencies
         ELSE drop_candidate
       END AS action
FROM col_meta cm
LEFT JOIN deps d ON d.schema_name=cm.schema_name AND d.table_name=cm.table_name AND d.legacy_col=cm.legacy_col
ORDER BY cm.table_name, cm.legacy_col;
