-- Generated from historical schema mapping
-- Rollback for column rename migration: snake_case -> camelCase
BEGIN;

DO $$
DECLARE
  r RECORD;
BEGIN
  FOR r IN
    SELECT *
    FROM (VALUES
      ('public', 'achievement_definitions', 'created_at', 'createdAt'),
      ('public', 'achievement_definitions', 'is_active', 'isActive'),
      ('public', 'achievement_definitions', 'is_repeatable', 'isRepeatable'),
      ('public', 'achievement_definitions', 'updated_at', 'updatedAt'),
      ('public', 'adaptive_recommendations', 'applied_at', 'appliedAt'),
      ('public', 'adaptive_recommendations', 'created_at', 'createdAt'),
      ('public', 'adaptive_recommendations', 'current_value', 'currentValue'),
      ('public', 'adaptive_recommendations', 'exercise_id', 'exerciseId'),
      ('public', 'adaptive_recommendations', 'input_snapshot', 'inputSnapshot'),
      ('public', 'adaptive_recommendations', 'model_version', 'modelVersion'),
      ('public', 'adaptive_recommendations', 'reason_code', 'reasonCode'),
      ('public', 'adaptive_recommendations', 'recommendation_type', 'recommendationType'),
      ('public', 'adaptive_recommendations', 'session_exercise_id', 'sessionExerciseId'),
      ('public', 'adaptive_recommendations', 'suggested_value', 'suggestedValue'),
      ('public', 'adaptive_recommendations', 'updated_at', 'updatedAt'),
      ('public', 'adaptive_recommendations', 'user_id', 'userId'),
      ('public', 'adaptive_recommendations', 'valid_until', 'validUntil'),
      ('public', 'ai_coach_messages', 'completion_tokens', 'completionTokens'),
      ('public', 'ai_coach_messages', 'conversation_key', 'conversationKey'),
      ('public', 'ai_coach_messages', 'created_at', 'createdAt'),
      ('public', 'ai_coach_messages', 'insight_id', 'insightId'),
      ('public', 'ai_coach_messages', 'model_name', 'modelName'),
      ('public', 'ai_coach_messages', 'prompt_tokens', 'promptTokens'),
      ('public', 'ai_coach_messages', 'session_id', 'sessionId'),
      ('public', 'ai_coach_messages', 'updated_at', 'updatedAt'),
      ('public', 'ai_coach_messages', 'user_id', 'userId'),
      ('public', 'ai_insights', 'created_at', 'createdAt'),
      ('public', 'ai_insights', 'insight_type', 'insightType'),
      ('public', 'ai_insights', 'model_version', 'modelVersion'),
      ('public', 'ai_insights', 'session_id', 'sessionId'),
      ('public', 'ai_insights', 'tokens_used', 'tokensUsed'),
      ('public', 'ai_insights', 'updated_at', 'updatedAt'),
      ('public', 'ai_insights', 'user_id', 'userId'),
      ('public', 'challenge_participants', 'challenge_id', 'challengeId'),
      ('public', 'challenge_participants', 'completed_at', 'completedAt'),
      ('public', 'challenge_participants', 'created_at', 'createdAt'),
      ('public', 'challenge_participants', 'joined_at', 'joinedAt'),
      ('public', 'challenge_participants', 'progress_value', 'progressValue'),
      ('public', 'challenge_participants', 'updated_at', 'updatedAt'),
      ('public', 'challenge_participants', 'user_id', 'userId'),
      ('public', 'challenges', 'challenge_type', 'challengeType'),
      ('public', 'challenges', 'created_at', 'createdAt'),
      ('public', 'challenges', 'creator_id', 'creatorId'),
      ('public', 'challenges', 'end_date', 'endDate'),
      ('public', 'challenges', 'is_public', 'isPublic'),
      ('public', 'challenges', 'start_date', 'startDate'),
      ('public', 'challenges', 'target_value', 'targetValue'),
      ('public', 'challenges', 'updated_at', 'updatedAt'),
      ('public', 'exercise_aliases', 'created_at', 'createdAt'),
      ('public', 'exercise_aliases', 'exercise_id', 'exerciseId'),
      ('public', 'exercise_aliases', 'normalized_alias', 'normalizedAlias'),
      ('public', 'exercise_aliases', 'updated_at', 'updatedAt'),
      ('public', 'exercise_personal_records', 'achieved_at', 'achievedAt'),
      ('public', 'exercise_personal_records', 'created_at', 'createdAt'),
      ('public', 'exercise_personal_records', 'exercise_id', 'exerciseId'),
      ('public', 'exercise_personal_records', 'source_session_id', 'sourceSessionId'),
      ('public', 'exercise_personal_records', 'source_workout_set_id', 'sourceWorkoutSetId'),
      ('public', 'exercise_personal_records', 'updated_at', 'updatedAt'),
      ('public', 'exercise_personal_records', 'user_id', 'userId'),
      ('public', 'exercises', 'created_at', 'createdAt'),
      ('public', 'exercises', 'is_archived', 'isArchived'),
      ('public', 'exercises', 'is_public', 'isPublic'),
      ('public', 'exercises', 'is_unilateral', 'isUnilateral'),
      ('public', 'exercises', 'owner_id', 'ownerId'),
      ('public', 'exercises', 'primary_muscle', 'primaryMuscle'),
      ('public', 'exercises', 'secondary_muscles', 'secondaryMuscles'),
      ('public', 'exercises', 'updated_at', 'updatedAt'),
      ('public', 'friendships', 'addressee_id', 'addresseeId'),
      ('public', 'friendships', 'created_at', 'createdAt'),
      ('public', 'friendships', 'requested_at', 'requestedAt'),
      ('public', 'friendships', 'requester_id', 'requesterId'),
      ('public', 'friendships', 'responded_at', 'respondedAt'),
      ('public', 'friendships', 'updated_at', 'updatedAt'),
      ('public', 'rest_timer_events', 'actual_rest_sec', 'actualRestSec'),
      ('public', 'rest_timer_events', 'created_at', 'createdAt'),
      ('public', 'rest_timer_events', 'event_type', 'eventType'),
      ('public', 'rest_timer_events', 'planned_rest_sec', 'plannedRestSec'),
      ('public', 'rest_timer_events', 'session_exercise_id', 'sessionExerciseId'),
      ('public', 'rest_timer_events', 'session_id', 'sessionId'),
      ('public', 'rest_timer_events', 'triggered_at', 'triggeredAt'),
      ('public', 'rest_timer_events', 'updated_at', 'updatedAt'),
      ('public', 'rest_timer_events', 'workout_set_id', 'workoutSetId'),
      ('public', 'social_reactions', 'created_at', 'createdAt'),
      ('public', 'social_reactions', 'post_id', 'postId'),
      ('public', 'social_reactions', 'reaction_type', 'reactionType'),
      ('public', 'social_reactions', 'updated_at', 'updatedAt'),
      ('public', 'social_reactions', 'user_id', 'userId'),
      ('public', 'social_workout_posts', 'created_at', 'createdAt'),
      ('public', 'social_workout_posts', 'is_deleted', 'isDeleted'),
      ('public', 'social_workout_posts', 'session_id', 'sessionId'),
      ('public', 'social_workout_posts', 'updated_at', 'updatedAt'),
      ('public', 'social_workout_posts', 'user_id', 'userId'),
      ('public', 'sync_events', 'client_event_id', 'clientEventId'),
      ('public', 'sync_events', 'conflict_data', 'conflictData'),
      ('public', 'sync_events', 'created_at', 'createdAt'),
      ('public', 'sync_events', 'device_id', 'deviceId'),
      ('public', 'sync_events', 'entity_id', 'entityId'),
      ('public', 'sync_events', 'entity_type', 'entityType'),
      ('public', 'sync_events', 'event_status', 'eventStatus'),
      ('public', 'sync_events', 'occurred_at', 'occurredAt'),
      ('public', 'sync_events', 'processed_at', 'processedAt'),
      ('public', 'sync_events', 'updated_at', 'updatedAt'),
      ('public', 'sync_events', 'user_id', 'userId'),
      ('public', 'training_program_weeks', 'created_at', 'createdAt'),
      ('public', 'training_program_weeks', 'program_id', 'programId'),
      ('public', 'training_program_weeks', 'updated_at', 'updatedAt'),
      ('public', 'training_program_weeks', 'week_number', 'weekNumber'),
      ('public', 'training_program_workouts', 'created_at', 'createdAt'),
      ('public', 'training_program_workouts', 'day_of_week', 'dayOfWeek'),
      ('public', 'training_program_workouts', 'order_index', 'orderIndex'),
      ('public', 'training_program_workouts', 'template_id', 'templateId'),
      ('public', 'training_program_workouts', 'updated_at', 'updatedAt'),
      ('public', 'training_program_workouts', 'week_id', 'weekId'),
      ('public', 'training_programs', 'author_id', 'authorId'),
      ('public', 'training_programs', 'created_at', 'createdAt'),
      ('public', 'training_programs', 'currency_code', 'currencyCode'),
      ('public', 'training_programs', 'is_archived', 'isArchived'),
      ('public', 'training_programs', 'is_marketplace_listed', 'isMarketplaceListed'),
      ('public', 'training_programs', 'is_public', 'isPublic'),
      ('public', 'training_programs', 'price_cents', 'priceCents'),
      ('public', 'training_programs', 'updated_at', 'updatedAt'),
      ('public', 'user_achievements', 'achievement_definition_id', 'achievementDefinitionId'),
      ('public', 'user_achievements', 'awarded_at', 'awardedAt'),
      ('public', 'user_achievements', 'created_at', 'createdAt'),
      ('public', 'user_achievements', 'updated_at', 'updatedAt'),
      ('public', 'user_achievements', 'user_id', 'userId'),
      ('public', 'user_profiles', 'birth_date', 'birthDate'),
      ('public', 'user_profiles', 'body_fat_percent', 'bodyFatPercent'),
      ('public', 'user_profiles', 'created_at', 'createdAt'),
      ('public', 'user_profiles', 'display_name', 'displayName'),
      ('public', 'user_profiles', 'first_name', 'firstName'),
      ('public', 'user_profiles', 'height_cm', 'heightCm'),
      ('public', 'user_profiles', 'last_name', 'lastName'),
      ('public', 'user_profiles', 'updated_at', 'updatedAt'),
      ('public', 'user_profiles', 'user_id', 'userId'),
      ('public', 'user_profiles', 'weight_kg', 'weightKg'),
      ('public', 'user_streaks', 'created_at', 'createdAt'),
      ('public', 'user_streaks', 'current_count', 'currentCount'),
      ('public', 'user_streaks', 'is_active', 'isActive'),
      ('public', 'user_streaks', 'last_event_date', 'lastEventDate'),
      ('public', 'user_streaks', 'longest_count', 'longestCount'),
      ('public', 'user_streaks', 'streak_start_date', 'streakStartDate'),
      ('public', 'user_streaks', 'streak_type', 'streakType'),
      ('public', 'user_streaks', 'updated_at', 'updatedAt'),
      ('public', 'user_streaks', 'user_id', 'userId'),
      ('public', 'users', 'created_at', 'createdAt'),
      ('public', 'users', 'deleted_at', 'deletedAt'),
      ('public', 'users', 'is_onboarded', 'isOnboarded'),
      ('public', 'users', 'telegram_user_id', 'telegramUserId'),
      ('public', 'users', 'telegram_username', 'telegramUsername'),
      ('public', 'users', 'updated_at', 'updatedAt'),
      ('public', 'workout_session_exercises', 'avg_rpe', 'avgRpe'),
      ('public', 'workout_session_exercises', 'best_estimated1_rm', 'bestEstimated1Rm'),
      ('public', 'workout_session_exercises', 'block_key', 'blockKey'),
      ('public', 'workout_session_exercises', 'block_type', 'blockType'),
      ('public', 'workout_session_exercises', 'created_at', 'createdAt'),
      ('public', 'workout_session_exercises', 'exercise_id', 'exerciseId'),
      ('public', 'workout_session_exercises', 'order_index', 'orderIndex'),
      ('public', 'workout_session_exercises', 'performed_sets', 'performedSets'),
      ('public', 'workout_session_exercises', 'session_id', 'sessionId'),
      ('public', 'workout_session_exercises', 'template_item_id', 'templateItemId'),
      ('public', 'workout_session_exercises', 'updated_at', 'updatedAt'),
      ('public', 'workout_session_exercises', 'volume_kg', 'volumeKg'),
      ('public', 'workout_sessions', 'created_at', 'createdAt'),
      ('public', 'workout_sessions', 'deleted_at', 'deletedAt'),
      ('public', 'workout_sessions', 'duration_seconds', 'durationSeconds'),
      ('public', 'workout_sessions', 'ended_at', 'endedAt'),
      ('public', 'workout_sessions', 'peak_estimated1_rm_kg', 'peakEstimated1RmKg'),
      ('public', 'workout_sessions', 'session_fatigue_score', 'sessionFatigueScore'),
      ('public', 'workout_sessions', 'source_device_id', 'sourceDeviceId'),
      ('public', 'workout_sessions', 'started_at', 'startedAt'),
      ('public', 'workout_sessions', 'sync_version', 'syncVersion'),
      ('public', 'workout_sessions', 'template_id', 'templateId'),
      ('public', 'workout_sessions', 'total_reps', 'totalReps'),
      ('public', 'workout_sessions', 'total_sets', 'totalSets'),
      ('public', 'workout_sessions', 'total_volume_kg', 'totalVolumeKg'),
      ('public', 'workout_sessions', 'training_program_workout_id', 'trainingProgramWorkoutId'),
      ('public', 'workout_sessions', 'updated_at', 'updatedAt'),
      ('public', 'workout_sessions', 'user_id', 'userId'),
      ('public', 'workout_sets', 'actual_rest_sec', 'actualRestSec'),
      ('public', 'workout_sets', 'created_at', 'createdAt'),
      ('public', 'workout_sets', 'distance_meters', 'distanceMeters'),
      ('public', 'workout_sets', 'duration_sec', 'durationSec'),
      ('public', 'workout_sets', 'estimated1_rm_kg', 'estimated1RmKg'),
      ('public', 'workout_sets', 'fatigue_score', 'fatigueScore'),
      ('public', 'workout_sets', 'is_completed', 'isCompleted'),
      ('public', 'workout_sets', 'session_exercise_id', 'sessionExerciseId'),
      ('public', 'workout_sets', 'set_order', 'setOrder'),
      ('public', 'workout_sets', 'set_type', 'setType'),
      ('public', 'workout_sets', 'suggested_rest_sec', 'suggestedRestSec'),
      ('public', 'workout_sets', 'updated_at', 'updatedAt'),
      ('public', 'workout_sets', 'weight_kg', 'weightKg'),
      ('public', 'workout_template_items', 'block_key', 'blockKey'),
      ('public', 'workout_template_items', 'block_type', 'blockType'),
      ('public', 'workout_template_items', 'created_at', 'createdAt'),
      ('public', 'workout_template_items', 'exercise_id', 'exerciseId'),
      ('public', 'workout_template_items', 'order_index', 'orderIndex'),
      ('public', 'workout_template_items', 'rest_seconds', 'restSeconds'),
      ('public', 'workout_template_items', 'target_reps_max', 'targetRepsMax'),
      ('public', 'workout_template_items', 'target_reps_min', 'targetRepsMin'),
      ('public', 'workout_template_items', 'target_rpe', 'targetRpe'),
      ('public', 'workout_template_items', 'target_sets', 'targetSets'),
      ('public', 'workout_template_items', 'target_weight_kg', 'targetWeightKg'),
      ('public', 'workout_template_items', 'template_id', 'templateId'),
      ('public', 'workout_template_items', 'updated_at', 'updatedAt'),
      ('public', 'workout_templates', 'created_at', 'createdAt'),
      ('public', 'workout_templates', 'estimated_min_sec', 'estimatedMinSec'),
      ('public', 'workout_templates', 'is_archived', 'isArchived'),
      ('public', 'workout_templates', 'is_public', 'isPublic'),
      ('public', 'workout_templates', 'updated_at', 'updatedAt'),
      ('public', 'workout_templates', 'user_id', 'userId')
    ) AS t(schema_name, table_name, old_col, new_col)
  LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = r.schema_name
        AND table_name = r.table_name
        AND column_name = r.old_col
    )
    AND NOT EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = r.schema_name
        AND table_name = r.table_name
        AND column_name = r.new_col
    ) THEN
      EXECUTE format('ALTER TABLE %I.%I RENAME COLUMN %I TO %I', r.schema_name, r.table_name, r.old_col, r.new_col);
    END IF;
  END LOOP;
END $$;

COMMIT;

-- Total column renames planned: 211
